name: Propagate issues to project board

on:
  issues:
    types: [opened]

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: shopify-ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.3.0
        with:
          project-url: https://github.com/orgs/Shopify/projects/3386
          github-token: ${{ secrets.CODE_SCALE_PROJECT_AUTOMATION_TOKEN }}
